export const actionTypes = {
  
  SET_LOGIN_PERMISSION_AND_ROLE: 'SET_LOGIN_PERMISSION_AND_ROLE',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_TOTAL_ITEMS: 'SET_TOTAL_ITEMS',
  SET_TOTAL_ITEMS_MAINMENU: 'SET_TOTAL_ITEMS_MAINMENU',
  SET_MAINMENU_DATA: 'SET_MAINMENU_DATA',

  SET_MAIN_CATEGORY_DATA: 'SET_MAIN_CATEGORY_DATA',
  SET_CATEGORY_DATA: 'SET_CATEGORY_DATA',
  SET_SUB_CATEGORY_DATA: 'SET_SUB_CATEGORY_DATA',
  SET_ROLE_DATA: 'SET_ROLE_DATA',
  SET_DEVICE_DATA: 'SET_DEVICE_DATA',
  SET_TIER_DATA: 'SET_TIER_DATA',
  SET_TIER_CONTINENT_DATA: 'SET_TIER_CONTINENT_DATA',
  SET_TIER_COUNTRY_DATA: 'SET_TIER_COUNTRY_DATA',
  SET_SUBMENU_DATA: 'SET_SUBMENU_DATA',
  SET_TOTAL_ITEMS_SUBMENU: 'SET_TOTAL_ITEMS_SUBMENU',
  ACCESS_TOKEN:'ACCESS_TOKEN',
  ROUTER_PATH:'ROUTER_PATH'
};
